# Generated by Django 4.1.4 on 2022-12-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0027_alter_client_id_alter_code_id_alter_responsetype_id_and_more'),
        ('oidc_provider', '0030_token_code_hash'),
    ]

    operations = [
    ]
